// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import VPath from './VPath.vue'
import VRect from './VRect.vue'

// Export components individually
export { VPath, VRect }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('VPath', VPath)
  Vue.component('VRect', VRect)
}

// Export the library as a plugin
export default { install: install }
